### PR TITLE
Fold origin/rebuild into release/1.1

### PR DESCRIPTION
**Pull request by VectorSatyr**
This will focus all development efforts into a single code base and prevent fragmentation of changes.

### CODE REVIEW

**Comment by nkrapivin** [comment]
Maybe redo all the rebuild changes manually instead of trying to fix merge conflicts?

**Comment by nkrapivin** [comment]
https://github.com/nkrapivin/SonicTimeTwisted/commit/c1cdb2b7fc58243586714f2a3c4dbbfb4214deba

I can make a PR.

**Comment by VectorSatyr** [comment]
@nkrapivin That's okay. Just let me handle things from here.

**Comment by VectorSatyr** [comment]
Something went wrong during the commit, so I've reverted it. I will attempt something else.

**Comment by VectorSatyr** [comment]
@nkrapivin I've decided that your fork of the build will probably work better for this. Have at it.

**Pull request merged**
