### PR TITLE
Feature/166 android tablet keyboard

### PR DESCRIPTION
**Pull request by AlexKhayrullin**

### CODE REVIEW

**Comment by upoverandgone** [comment]
I do I use keyboard on android? I play on my Chromebook but the keyboard doesn't work.

**Comment by AlexKhayrullin** [comment]
Select "BT/USB device" as your input method. You'll have to remap your keys too, since the original mapping is for a gamepad.

If that doesn't work, then... I don't know, I'm sorry. I tested this with an Android tablet with as keyboard (Samsung Galaxy Tab S7) , I don't have a Chromebook...

**Comment by upoverandgone** [comment]
I'm not sure why it's not working it use to work with a controller but now it doesn't and the keyboard doesn't work either I did what you said.

**Comment by AlexKhayrullin** [comment]
Since I don't own a Chromebook for testing (not to mention, I quit the project) I won't be able to help you. I am really sorry.

I created a new issue: https://github.com/overbound/SonicTimeTwisted/issues/272 . Let's hope the Open Source magic works and someone manages to help you out ^^'.

**Comment by upoverandgone** [comment]
Not sure if you're still on this but apparently, I have to plug in a controller and then it will let me use my keyboard

**Pull request merged**
