### PR TITLE
change sprites

### PR DESCRIPTION
**Pull request by romulok77**
Some sprites changed. read last comment in #93 for some details and know what was changed before looking at the files

### CODE REVIEW

**Review by VectorSatyr — CHANGES_REQUESTED** [review]
**sprKnucklesSSJump, sprSonicSSJump** - "There was no need to make Sonic and Knuckles' jumping animations the same as Tails; Tails has a unique "blob"-like jumping animation because he has fur and no spikes, but Sonic and Knuckles' jumping sprites usually have them visible with only flashes of solid color appearing once every ... four frames, I guess? The original sprites might arguably need some touch-ups color-wise (even though they look perfectly fine in motion,) but replacing them entirely with Tails-like animations is not the solution." @AlexKhayrullin

**sprSonicDead** - "Having discussed it, we're going to use the original sprites after all; we have an animation in mind that might work better with them. Never mind that the "eyes rolled back" face is used for drowning at the moment, it's something that will be fixed with code." @AlexKhayrullin

**sprSonicLook, sprSuperSonicLook** - "Sorry, the original sprite looks better." @AlexKhayrullin

**sprSuperSonicDead** - Changes will align with the decision regarding **sprSonicDead**.

**sprTailsFlight** - This will be updated by us to look closer to Tails' Sonic 3 frames.

**sprSonicStandRotate, sprSuperSonicStandRotate** - "While the changes to the spikes are OK and the hands move a little less, editing Sonic's mouth so it consistently stays on the right side of his head was not necessary." @AlexKhayrullin

**sprSuperSonic3DTurn** - "Frames are clearly reordered or missing. Also, the frame seen from behind is very clearly cropped at the top (you can clearly see where the sprite ends) even though it might have been fine in motion, Sonic suddenly turning around due to missing sprites immediately after it appears ruins the spectacle." @AlexKhayrullin

**sprTailsRun** - "The slower running animation could benefit from having Tails' legs move like in the original games. The faster running animation can be left as-is." @AlexKhayrullin

**sprTailsStandRotate** - "The rotation is visibly smoother, but the frame with Tails staring directly at the player seems to have been moved one pixel lower than the rest." @AlexKhayrullin

**sprSuperSonicCrouch, sprSuperSonicFloating, sprSuperSonicGetAir, sprSuperSonicLook** - Conditional to **sprSuperSonic3DTurn** and **sprSuperSonicStandRotate** getting changed; otherwise, it's a no.

**Bubble Shield Animation Speed** - Not a noticeable improvement; did not need to change.

_All other changes are accepted._

**Comment by romulok77** [comment]
Please look last comment in #93

**Comment by romulok77** [comment]
well, it seems that the latter was not changed last time, that must be why it was rejected. 😅

**Comment by VectorSatyr** [comment]
> well, it seems that the latter was not changed last time, that must be why it was rejected. 😅

We saw the intended sprite changes.

**Comment by romulok77** [comment]
> > well, it seems that the latter was not changed last time, that must be why it was rejected. 😅
> 
> @romulok77 We saw the intended sprite changes. They are still rejected.

ok, after you review the changes that I reversed, I put these items back to the original.

**Review by VectorSatyr — CHANGES_REQUESTED** [review]
**sprSonicLook, sprSuperSonicLook** - See previous comment.

**sprSonicDead, sprSuperSonicDead** - "Thanks, but we are not keeping the first frame in both cases, please delete it." @AlexKhayrullin

**sprSonicStandRotate, sprSuperSonicStandRotate** - "They have been kept updated, and have Super Sonic's raised spikes, but other sprites such as **sprSuperSonicCrouch, sprSuperSonicFloating, sprSuperSonicGetAir, sprSuperSonic3DTurn, etc.** have been reverted. We now have an inconsistency where Super Sonic either has his spikes raised or not depending on the sprite." @AlexKhayrullin

**sprTailsStandRotate** - "The way you describe it also means the PR is not ready to be merged as-is, there is work to do." @AlexKhayrullin

**sprTailsFlight** - Hasn't been reverted.

_All other changes are accepted._

**Comment by romulok77** [comment]
Got it

**Pull request merged**
