### PR TITLE
PT-BR translation

### PR DESCRIPTION
**Pull request by romulok77**
PT-BR translations with necessary files.

### CODE REVIEW

**Comment by AlexKhayrullin** [comment]
Hi :)

I'm closing this PR because something seems to be wrong with the main GMX file, merging this PR in this state would be completely rewriting it, and introducing a lot of new issues to the project. I don't know why though, I'd be tempted to say that you haven't pulled in a while, but you did include the latest addition to the files, which is the "SHIELD" string, so I really don't know what happened there.

However don't worry, I'm accepting the translation, so I'll be adding the files manually on my end. The only other modification I'll make is one I just made to the English string (and didn't commit yet) : replacing the ellipses as single characters in Metal Sonic's lines with three points.

**Comment by romulok77** [comment]
it's a shame, I even used the recent project, this error certainly came from my computer, when saving the changes something must have happened, I don't know.

**Comment by romulok77** [comment]
at least sprites don't need to update the .gmx file, do they?

**Comment by AlexKhayrullin** [comment]
No, AFAIK they only update their respective GMX files.

I guess in this case, there's a lot of stuff added to the beginning of the main GMX file, so much so that Git can't keep track of it.

I just verified the parents commits and everything, you did in fact use the latest commit. You know what, I'll back up my main GMX file and try merging. It really looks like it's more Git that has an issue than anything else.

**Comment by AlexKhayrullin** [comment]
I ran both the original and the merged file through Meld, they are identical except for an added block of XML that matches the files you added.

I don't get it ^^'

**Comment by romulok77** [comment]
good to see this, thanks 😅👍. later I will open another PR with the sprites, but not now because there are others that I think should improve

**Pull request merged**
