### PR TITLE
"New" sprites and PT-BR translation/1.1

### PR DESCRIPTION
**Pull request by romulok77**
change of some sprites (including boss gollen and FireFly #89 and something of #93  ) and few animations along with the most recent Brazilian Portuguese translation. 

And a suggestion, when switching to dual mode, a switch control appears indicating the player about the first and second device. but I only drew anything so far. this would be below the line: press a button of first or second device, 
https://ibb.co/6yqNRp6

my god I hope everything is here

### CODE REVIEW

**Comment by AlexKhayrullin** [comment]
Hi and thanks for the PR :)

A couple of comments:
 - Usually, you don't close an issue until after the PR is accepted ;)
 - Thanks for the translation!
 - It apparently wasn't clear enough in the original English strings, but not calling Joy-Cons by their name in-game was a conscious choice on my part, I wanted to keep it generic... just in case. You know how ridiculous Nintendo can be, I'd rather steer away from clearly naming anything made by them (the one time "Joy-Con" appears in the menu as I've coded it is when the name is provided by the Joy-Con itself), and the irony of it being in the context of a fangame is not lost on me. Also, I get what you are trying to do with the three Joy-Con pictures, unfortunately that's not exactly compatible with the Android library: it can't tell them apart until both of them are connected, when one of them is connected it just knows there's one of the two, it does not care which one of the two it is.
 - With the sheer amount of updated graphics, I don't think I have a moral right to approve this on my own. I'll forward this to the rest of the team.
 - Can you please tell  me who to credit for all these graphics and how (like, what format? full name? just the username? both?), I guess you are behind most of it, and the Golem and the Firefly were reshaded by Bennascar.

**Comment by romulok77** [comment]
I understand, if you are going to credit, put my name: Romulo Santos

**Comment by nkrapivin** [comment]
image
intname is the language code so should be `pt`, I forgot about dialects when implementing this...

**Comment by romulok77** [comment]
> imagem
> intname é o código do idioma, então deveria ser `pt`, esqueci os dialetos ao implementar isso ...

Ok, when I can, I change this part. it was already 'pt-br', but for some reason I put the current name

**Comment by AlexKhayrullin** [comment]
Hi.

There has been some discussion on the subject on your contributions.
I'll close this PR because it has two completely unrelated big contributions, which is not a good practice, and it makes it hard to discuss. Can you please resubmit this as two different PRs, one for translations and one for graphics?

**Comment by romulok77** [comment]
Ok, no problem

**Pull request closed without merging**
