### PR TITLE
Merge origin/rebuild

### PR DESCRIPTION
**Pull request by nkrapivin**
I've manually copied over last fixes from rebuild that weren't committed in release/1.1.

+ another fix for YYC to fix platforms and time posts, with these, you can actually play the game in YYC!!!

I'll build two android .apks, one on VM, and one on YYC, both with debug overlay enabled.
Then I (and maybe @AlexKhayrullin) will compare the performance and see if it's actually reasonable to use YYC.

Builds: ~~https://drive.google.com/folderview?id=AAAAAAAAAAAAAAAAAAA~~

An .apk from a random google drive folder is NOT an official release.

### CODE REVIEW

**Comment by nkrapivin** [comment]
Okay I've tried both VM and YYC build, YYC runs [way] faster.

Please @AlexKhayrullin DL the .apks now if you want, I'll take down the folder, the YT videos are using builds from my folder (because of the debug overlay enabled), I didn't know someone would actually record these dev builds on video...

**Comment by AlexKhayrullin** [comment]
Downloaded. You can take the folder down :)

**Comment by nkrapivin** [comment]
image
Done.

~~and then I realized a Discord server for STT isn't a bad idea, you can make a #secret-dev channel and share any dev builds.~~

**Review by VectorSatyr — APPROVED** [review]
I'm not noticing any issues that are relevant to the changes in this commit.

**Review by AlexKhayrullin — APPROVED** [review]

**Pull request merged**
